"""empty message

Revision ID: 78578c3af017
Revises: be4e2e19413e
Create Date: 2019-05-31 18:55:03.943817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78578c3af017'
down_revision = 'be4e2e19413e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
